development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: heroku_slow_push_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: heroku_slow_push_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: heroku_slow_push_production
  pool: 5
